version: '4'

services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 2240512
      MYSQL_DATABASE: test
    ports:
      - 3308:3306